name: Deploy to oidc-tieki-test

on:
  push:
    branches: [ "db-remove-non-admins" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: nikitaessine
        password: ${{ secrets.OIDC }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: nikitaessine/oidc:latest