name: Deploy to production

on:
  release:
    types: [published]

jobs:

  test:
    permissions:
      contents: write
    uses: ./.github/workflows/test.yaml

  build:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./prod.Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tieki-prod:latest
