name: Deploy to staging

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    env:
      MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
      OIDC_REDIRECT_URI: ${{ secrets.OIDC_REDIRECT_URI }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: ./.github/workflows/test.yaml
  
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
