name: tests

on: [pull_request, workflow_call]

jobs:

  eslint:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4

    - name: Install node packages
      run: npm install

    - name: Run eslint
      run: npm run lint

  robot:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4

    - name: Install node packages
      run: npm install

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Robot Framework & Selenium
      run: pip install robotframework && pip install robotframework-seleniumlibrary && pip install selenium==4.9.1

    - name: Run Robot tests
      run: sh tests/robot/actions_run_robot_tests.sh
