name: Run tests

on: [pull_request, workflow_call]


jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build project for eslint
      run: cd frontend && npm install

    - name: Run eslint
      run: cd frontend && npm run lint
