name: tests

on: [pull_request, workflow_call, workflow_dispatch]

jobs:

  eslint-autofix:

    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install node packages
      run: npm install

    - name: Run lint-fix
      run: npm run lint-fix

    - name: Auto commit & push lint-fix
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto-fix ESLint
        file_pattern: '*.js *.jsx'

  eslint-main:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4

    - name: Install node packages
      run: npm install

    - name: Run ESLint
      run: npm run lint

  jest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install node packages
      run: npm install

    - name: Run tests
      run: npm run test

  robocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Robot Framework, SeleniumLibrary & Robocop
      run: pip install robotframework && pip install robotframework-seleniumlibrary && pip install selenium==4.9.1 && pip install robotframework-robocop

    - name: Run Robocop Checks
      run: robocop

  robot-chrome:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --name mongodb

    steps:
    - uses: actions/checkout@v4

    - name: Install node packages
      run: npm install

    - name: Insert JSON to database
      run: npm run init-e2e

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Robot Framework & SeleniumLibrary
      run: pip install robotframework && pip install robotframework-seleniumlibrary && pip install selenium==4.9.1 && pip install robotframework-requests

    - name: Run Robot tests in headless chrome
      run: sh tests/robot/actions_run_robot_tests.sh headlesschrome
